### ISSUE TITLE
关于 Sylph-Few-Shot-Detection 复现项目的交流与问题解决

### ISSUE THREAD

**Issue by snow102** [RockJim2001/Code#1]
尊敬的RockJim2001，您好，

原谅我用这种方式打扰您，最近在复现 Sylph A Hypernetwork Framework for Few-shot Object Detection项目，并遇到了一些问题。在GitHub的评论区看到您提到成功解决了与 COCO 数据集上的 AP 值不理想的问题，因此想与您交流并请教相关经验。

具体来说，我的实验结果与论文中的实验数据存在较大差距，怀疑可能与训练设备有关。我已经尝试了用4090显卡，但效果仍不理想。因此，特别希望了解您在解决此问题时的具体步骤和经验。

如果方便，您能分享一些建议或思路吗？不胜感激！

非常感谢您的帮助！

**Comment by RockJim2001** [comment]
结果跟显卡无关！这篇文章的代码现在已经没有人去维护了，因为作者从meta-ai离职之后也没办法复现，我觉得几乎是没人复现出来论文中的结果。下面是没法复现论文结果的原因：
1、论文中pretrain阶段采用了三种数据增强方案：Default、Aug、All。这三种数据增强方法中只有第一种Default我们能够实现，就是采用框架默认的两种数据增强方式；第二种Aug中的RandAug增强方法这篇论文公布代码里面也没有相关的代码，只有一个RandAugImage方法，我研究了半天也没琢磨透这两者是否等同；第三种All中采用了IG-50M这个Backbone，通过阅读提出这个Backbone的论文可以发现，还是meta-ai发表的，这个权重也是内部的数据没有公开。
2、论文中的meta-train阶段不是采用3-way 5-shot的这种方式进行meta-learning学习的嘛，虽然在代码的config文件中有MODEL.META_LEARN.CLASS这个配置项，但是通过详细阅读代码实现会发现这个配置没有起到作用。代码中的way是通过总的batch_size 除以 gpus 得到每一块gpu上的batch_size来确定的，所以meta-train阶段对卡的数量有很高的要求，对卡显存大小没有多少要求，我的卡只有两张Quadro RTX5000，没办法进行复现。因为代码中会自动根据你gpus的数量来自动调整总迭代次数，太浪费时间了。
3、我曾经在4张A100上复现过COCO数据集上的10-shot结果，但是跟论文也差的有点多，现在没办法有这么好的白嫖设备了。
4、我后来也花费了很多时间去复现论文中的结果（一般都在COCO数据集上），只是复现了TFA* 和TFA-ours这种没有Code-Generator的结果。

最后，我们组设备严重匮乏，时间也耗不起了，应该不会再去复现论文结果，如果你们组的设备比较硬核的话，可以去试着复现一下，复现出来的话可以多进行交流，哪怕是一个结果，谢谢！

发件人：snow102 ***@***.***>
发送日期：2024-11-08 21:21:08
收件人：RockJim2001/Code ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[RockJim2001/Code] 关于 Sylph-Few-Shot-Detection 复现项目的交流与问题解决 (Issue #1)

尊敬的RockJim2001，您好，
原谅我用这种方式打扰您，最近在复现 Sylph A Hypernetwork Framework for Few-shot Object Detection项目，并遇到了一些问题。在GitHub的评论区看到您提到成功解决了与 COCO 数据集上的 AP 值不理想的问题，因此想与您交流并请教相关经验。
具体来说，我的实验结果与论文中的实验数据存在较大差距，怀疑可能与训练设备有关。我已经尝试了用4090显卡，但效果仍不理想。因此，特别希望了解您在解决此问题时的具体步骤和经验。
如果方便，您能分享一些建议或思路吗？不胜感激！
非常感谢您的帮助！

**Comment by snow102** [comment]
尊敬的RockJim2001老师，

感谢您的详细回复，您提到的复现难点和原因让我受益良多，确实解释了我在复现过程中的一些困惑。尤其是关于数据增强和meta-train配置的实现问题，这些对结果影响很大却难以控制的细节让我更明白复现困难的所在。

我们实验设备有限，前期只是用了一张显卡，尤其在多卡要求上条件不够充分，目前可能难以完成这部分实验的深入复现。我会继续关注该领域的研究动态，如果您之后有新的进展，非常欢迎交流！

**Comment by RockJim2001** [comment]
好哒好哒，欢迎交流，互相学习！

发件人：snow102 ***@***.***>
发送日期：2024-11-11 11:08:34
收件人：RockJim2001/Code ***@***.***>
抄送人：RockJim2001 ***@***.***>,Comment ***@***.***>
主题：Re: [RockJim2001/Code] 关于 Sylph-Few-Shot-Detection 复现项目的交流与问题解决 (Issue #1)

尊敬的RockJim2001老师，
感谢您的详细回复，您提到的复现难点和原因让我受益良多，确实解释了我在复现过程中的一些困惑。尤其是关于数据增强和meta-train配置的实现问题，这些对结果影响很大却难以控制的细节让我更明白复现困难的所在。
我们实验设备有限，前期只是用了一张显卡，尤其在多卡要求上条件不够充分，目前可能难以完成这部分实验的深入复现。我会继续关注该领域的研究动态，如果您之后有新的进展，非常欢迎交流！
